**WORKING WITH NUMPY**

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


For more than one dimension

In [ ]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
a = np.array([1,2,3,4], ndmin=2)
print(a)

[[1 2 3 4]]


Following examples shows the use of structural data type

In [ ]:
import numpy as np
dt = np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [ ]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)],dtype=dt)
print(a)

[(10,) (20,) (30,)]


In [ ]:
dt=np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)],dtype=dt)
print(a['age'])

[10 20 30]


**NUMPY ARRAY ATTRIBUTES**

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.arange(4)
print(a)
print(a.ndim)

[0 1 2 3]
1


In [ ]:
a = np.empty([3,2],dtype=int)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.ones([3,2],dtype=float,order='c')
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


**INSPECTING ARRAY**

In [ ]:
a = np.array([[1,2],[3,4]])

print(a)
print(a.shape)
print(len(a))
print(a.ndim)
print(a.size)
print(a.dtype)

[[1 2]
 [3 4]]
(2, 2)
2
2
4
int64


**AGGREGRATE FUNCTIONS**

In [ ]:
a = np.arange(7,dtype=int)

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))

21
0
6
3.0
3.0
